import type { SchedulingReasonCode } from '../shared/types.ts';
export const priorityText = {
  'zh-CN': {
    title: '优先级',
    language: '优先级语言 / Priority language',
    reason: '优先级原因',
    missing: '未记录',
    level: '选择优先级',
    save: '保存优先级',
    saving: '保存中…',
    saved: '优先级已保存',
    refreshFailed: '优先级已保存，但刷新失败，请刷新页面',
    failed: '保存失败，请重试',
    conflict: '优先级已被其他操作更新，已刷新；请核对后重新保存',
    history: '优先级历史',
    created: '创建',
    user: '本地用户',
    pm: 'PM',
    schedule: '当前项目认领顺序',
    scope:
      '仅列出此刻满足全部认领条件的任务；受项目轮转影响，不承诺开工时间。优先级不控制评审或合并，不抢占运行中的工作。',
    empty: '此刻没有可认领任务，请查看各任务的等待条件。',
    eligible: '此刻可认领',
    waiting: '认领条件',
    refresh: '刷新认领顺序',
    updated: '更新时间',
    rotation: '项目轮转顺序',
    source: '源消息',
    run: 'Run',
    stage: '阶段',
    scheduleFailed: '读取认领顺序失败，请刷新',
  },
  en: {
    title: 'Priority',
    language: 'Priority language / 优先级语言',
    reason: 'Priority reason',
    missing: 'Not recorded',
    level: 'Select priority',
    save: 'Save priority',
    saving: 'Saving…',
    saved: 'Priority saved',
    refreshFailed: 'Priority saved, but refresh failed. Please reload the page.',
    failed: 'Save failed; please retry',
    conflict: 'Priority changed elsewhere. Refreshed; review and save again.',
    history: 'Priority history',
    created: 'Created',
    user: 'Local user',
    pm: 'PM',
    schedule: 'Current project claim order',
    scope:
      'Only tasks meeting every claim condition now are listed. Project rotation applies; this is not a promised start time. Priority does not control reviews or merges and never preempts running work.',
    empty: 'No claimable tasks now. See each task’s waiting conditions.',
    eligible: 'Claimable now',
    waiting: 'Claim conditions',
    refresh: 'Refresh claim order',
    updated: 'Updated',
    rotation: 'Project rotation order',
    source: 'Source message',
    run: 'Run',
    stage: 'Stage',
    scheduleFailed: 'Could not read claim order; please refresh',
  },
};
export const schedulingReasonText: Record<'zh-CN' | 'en', Record<SchedulingReasonCode, string>> = {
  'zh-CN': {
    paused: '任务已暂停',
    blocked: '任务被阻塞',
    feedback: '等待处理反馈',
    stage: '当前阶段不能由 Dev 认领',
    unauthorized: '仓库尚未授权',
    repositoryBlocked: '仓库被阻塞',
    workSwitch: '仓库开工开关关闭',
    activeRun: '已有活动 Run',
    dependency: '前置任务未完成',
    globalCapacity: '等待全局执行名额',
    projectCapacity: '等待项目执行名额',
    repositoryCapacity: '等待仓库执行名额',
  },
  en: {
    paused: 'Task paused',
    blocked: 'Task blocked',
    feedback: 'Pending feedback',
    stage: 'Stage cannot be claimed by Dev',
    unauthorized: 'Repository not authorized',
    repositoryBlocked: 'Repository blocked',
    workSwitch: 'Repository work switch closed',
    activeRun: 'Active Run exists',
    dependency: 'Dependency unfinished',
    globalCapacity: 'Waiting for global capacity',
    projectCapacity: 'Waiting for project capacity',
    repositoryCapacity: 'Waiting for repository capacity',
  },
};
